"""insider transactions from SEC Form 4

Officers and directors must report their own trades within two business days,
and EDGAR publishes those filings free and within minutes. This table is the
local record of them.

`instrument_id` is nullable on purpose: most Form 4 issuers are US tickers we do
not hold, and a filing whose ticker resolves to nothing is still worth keeping —
the resolution is retried as the catalogue grows, rather than the filing being
discarded and the gap being invisible.

Unique on (accession_number, line_index) so re-polling the feed is idempotent:
EDGAR indexes one filing under every CIK it involves, so the same document is
reachable by several paths and will be seen more than once

Revision ID: ef244a4757ff
Revises: d3b8f26a91c7
Create Date: 2026-07-29 01:11:02.124421+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "ef244a4757ff"
down_revision: str | None = "d3b8f26a91c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insider_transactions",
        sa.Column("accession_number", sa.String(length=32), nullable=False),
        sa.Column("line_index", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=True),
        sa.Column("issuer_ticker", sa.String(length=16), nullable=True),
        sa.Column("issuer_name", sa.String(length=200), nullable=True),
        sa.Column("insider_name", sa.String(length=200), nullable=True),
        sa.Column("officer_title", sa.Text(), nullable=True),
        sa.Column("is_officer", sa.Boolean(), nullable=False),
        sa.Column("is_director", sa.Boolean(), nullable=False),
        sa.Column("is_ten_percent_owner", sa.Boolean(), nullable=False),
        sa.Column("is_c_suite", sa.Boolean(), nullable=False),
        sa.Column("transaction_code", sa.String(length=2), nullable=True),
        sa.Column("acquired_disposed", sa.String(length=1), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=True),
        sa.Column("filed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shares", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("price_per_share", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("value_usd", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("shares_owned_after", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("is_10b5_1_plan", sa.Boolean(), nullable=False),
        sa.Column("is_signalling", sa.Boolean(), nullable=False),
        sa.Column("filing_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_insider_transactions_instrument_id_instruments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insider_transactions")),
        sa.UniqueConstraint(
            "accession_number", "line_index", name="uq_insider_transactions_accession_line"
        ),
    )
    op.create_index(
        op.f("ix_insider_transactions_filed_at"), "insider_transactions", ["filed_at"], unique=False
    )
    op.create_index(
        "ix_insider_transactions_instrument_date",
        "insider_transactions",
        ["instrument_id", "transaction_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insider_transactions_instrument_id"),
        "insider_transactions",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insider_transactions_is_signalling"),
        "insider_transactions",
        ["is_signalling"],
        unique=False,
    )
    op.create_index(
        "ix_insider_transactions_ticker", "insider_transactions", ["issuer_ticker"], unique=False
    )
    op.create_index(
        op.f("ix_insider_transactions_transaction_date"),
        "insider_transactions",
        ["transaction_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_insider_transactions_transaction_date"), table_name="insider_transactions"
    )
    op.drop_index("ix_insider_transactions_ticker", table_name="insider_transactions")
    op.drop_index(op.f("ix_insider_transactions_is_signalling"), table_name="insider_transactions")
    op.drop_index(op.f("ix_insider_transactions_instrument_id"), table_name="insider_transactions")
    op.drop_index("ix_insider_transactions_instrument_date", table_name="insider_transactions")
    op.drop_index(op.f("ix_insider_transactions_filed_at"), table_name="insider_transactions")
    op.drop_table("insider_transactions")
    # ### end Alembic commands ###
