"""market regime snapshots

Revision ID: f7184b40649a
Revises: f8c1a4d2e703
Create Date: 2026-07-31 01:26:02.785769+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "f7184b40649a"
down_revision: str | None = "f8c1a4d2e703"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_regime_snapshots",
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("vix", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("breadth_above_200dma", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("breadth_sample", sa.Integer(), nullable=True),
        sa.Column("sp500_uptrend", sa.Boolean(), nullable=True),
        sa.Column("world_uptrend", sa.Boolean(), nullable=True),
        sa.Column("sp500_vs_200dma", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("yield_curve_10y2y", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("yield_curve_10y3m", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("buffett_indicator", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("risk_factor", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("posture", sa.String(length=32), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_regime_snapshots")),
        sa.UniqueConstraint("as_of", name="uq_market_regime_snapshots_as_of"),
    )
    op.create_index(
        op.f("ix_market_regime_snapshots_as_of"), "market_regime_snapshots", ["as_of"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_regime_snapshots_as_of"), table_name="market_regime_snapshots")
    op.drop_table("market_regime_snapshots")
    # ### end Alembic commands ###
