"""live ceilings on risk configuration

Revision ID: 32211713f911
Revises: ea234ccbc752
Create Date: 2026-07-20 11:35:28.689736+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '32211713f911'
down_revision: str | None = 'ea234ccbc752'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('live_arming_sessions', 'mode',
               existing_type=sa.VARCHAR(length=24),
               server_default=None,
               existing_nullable=False)
    op.add_column('risk_configurations', sa.Column('max_live_capital', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('risk_configurations', sa.Column('max_daily_loss', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_configurations', 'max_daily_loss')
    op.drop_column('risk_configurations', 'max_live_capital')
    op.alter_column('live_arming_sessions', 'mode',
               existing_type=sa.VARCHAR(length=24),
               server_default=sa.text("'live_approval_required'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
