"""strategy layer

Revision ID: 194cbd855af8
Revises: d72851034a39
Create Date: 2026-07-19 15:28:15.342342+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.models.base

revision: str = '194cbd855af8'
down_revision: str | None = 'd72851034a39'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_configurations',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('operating_mode', sa.String(length=24), nullable=False),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('params', app.models.base.JSONBOrJSON(), nullable=True),
    sa.Column('universe', app.models.base.JSONBOrJSON(), nullable=True),
    sa.Column('account_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_configurations')),
    sa.UniqueConstraint('name', name='uq_strategy_configurations_name')
    )
    op.create_table('strategy_runs',
    sa.Column('configuration_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instruments_considered', sa.Integer(), nullable=False),
    sa.Column('signals_generated', sa.Integer(), nullable=False),
    sa.Column('proposals_created', sa.Integer(), nullable=False),
    sa.Column('executed', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('selection_reason', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['strategy_configurations.id'], name=op.f('fk_strategy_runs_configuration_id_strategy_configurations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_runs'))
    )
    op.create_index(op.f('ix_strategy_runs_configuration_id'), 'strategy_runs', ['configuration_id'], unique=False)
    op.create_index('ix_strategy_runs_kind_started', 'strategy_runs', ['kind', 'started_at'], unique=False)
    op.create_table('strategy_decisions',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('configuration_id', sa.Uuid(), nullable=True),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('conviction', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metrics', app.models.base.JSONBOrJSON(), nullable=True),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['strategy_configurations.id'], name=op.f('fk_strategy_decisions_configuration_id_strategy_configurations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_strategy_decisions_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], name=op.f('fk_strategy_decisions_proposal_id_trade_proposals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], name=op.f('fk_strategy_decisions_run_id_strategy_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_decisions'))
    )
    op.create_index(op.f('ix_strategy_decisions_configuration_id'), 'strategy_decisions', ['configuration_id'], unique=False)
    op.create_index('ix_strategy_decisions_instrument', 'strategy_decisions', ['instrument_id'], unique=False)
    op.create_index('ix_strategy_decisions_outcome', 'strategy_decisions', ['outcome'], unique=False)
    op.create_index('ix_strategy_decisions_run', 'strategy_decisions', ['run_id'], unique=False)
    op.alter_column('risk_configurations', 'trailing_stop_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('risk_configurations', 'max_holding_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_configurations', 'max_holding_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('risk_configurations', 'trailing_stop_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index('ix_strategy_decisions_run', table_name='strategy_decisions')
    op.drop_index('ix_strategy_decisions_outcome', table_name='strategy_decisions')
    op.drop_index('ix_strategy_decisions_instrument', table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_configuration_id'), table_name='strategy_decisions')
    op.drop_table('strategy_decisions')
    op.drop_index('ix_strategy_runs_kind_started', table_name='strategy_runs')
    op.drop_index(op.f('ix_strategy_runs_configuration_id'), table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_table('strategy_configurations')
    # ### end Alembic commands ###
