"""retune: reversal weight down, tighter stop, smaller position cap

Three operator decisions, no schema change.

  * `reversal` 0.17 -> 0.05, with the freed weight going to `price_cheapness`
    (0.17 -> 0.29). Reversal rewards "reclaimed the 20-day average", and that
    average is the Bollinger middle band the mean-reversion strategy *sells*
    at — so at 0.17 the ranking was selecting for stocks sitting in the
    strategy's exit zone. Measured on a live top 20: eleven at or above the
    middle band, none below the lower one, hence no entry candidates at all.
    `price_cheapness` rewards being *at* a low, which is what the entry needs.

  * `atr_stop_multiplier` 2.0 -> 1.75. The exit target (band to mean, ~2 sigma)
    was smaller than the stop (2x ATR, ~2.4-3 sigma), so the strategy risked
    more than it played for. A tighter stop improves the ratio at the cost of
    more stop-outs.

  * `max_position_pct` 0.10 -> 0.05. With `max_open_positions` at 20, a 10% cap
    implied 200% of equity: cash bound at roughly 13 positions and allocation
    went to whichever signalled first rather than whichever ranked best. At 5%
    the two settings are consistent

Revision ID: 714ed9659c98
Revises: b6372c75004c
Create Date: 2026-07-29 15:44:56.699507+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "714ed9659c98"
down_revision: str | None = "b6372c75004c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_NEW_WEIGHTS = (
    '{"fundamental_value": 0.30, "price_cheapness": 0.29, "reversal": 0.05, '
    '"quality": 0.12, "sector": 0.09, "insider": 0.15}'
)
_OLD_WEIGHTS = (
    '{"fundamental_value": 0.30, "price_cheapness": 0.17, "reversal": 0.17, '
    '"quality": 0.12, "sector": 0.09, "insider": 0.15}'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.execute(f"UPDATE scanner_configurations SET factor_weights = '{_NEW_WEIGHTS}'::jsonb")
    op.execute("UPDATE risk_configurations SET atr_stop_multiplier = 1.75, max_position_pct = 0.05")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"UPDATE scanner_configurations SET factor_weights = '{_OLD_WEIGHTS}'::jsonb")
    op.execute("UPDATE risk_configurations SET atr_stop_multiplier = 2.0, max_position_pct = 0.10")
    pass
    # ### end Alembic commands ###
