"""primary score and value weighting

Revision ID: 0f75d2ac25fb
Revises: 4c555a89a446
Create Date: 2026-07-18 03:12:10.645591+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0f75d2ac25fb"
down_revision: str | None = "4c555a89a446"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (the tables are already populated),
    # so the NOT NULL constraint is satisfiable. New rows get their value from
    # the application. Defaults: momentum-primary (1/0) for configs; existing
    # results predate the primary score, so seed it to their core-based band via
    # a follow-up UPDATE below.
    op.add_column(
        "scanner_configurations",
        sa.Column(
            "momentum_weight", sa.Numeric(precision=12, scale=6), nullable=False, server_default="1"
        ),
    )
    op.add_column(
        "scanner_configurations",
        sa.Column(
            "value_weight", sa.Numeric(precision=12, scale=6), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "scanner_results",
        sa.Column(
            "primary_score", sa.Numeric(precision=12, scale=6), nullable=False, server_default="0"
        ),
    )
    # Existing results: their momentum core *was* the primary score under the old
    # momentum-only behaviour, so backfill it rather than leaving a misleading 0.
    op.execute("UPDATE scanner_results SET primary_score = core_score")

    # Drop the server defaults now that existing rows are backfilled: going
    # forward the application supplies these values, and keeping a DB-side default
    # would diverge from the model (the model has only a Python default).
    op.alter_column("scanner_configurations", "momentum_weight", server_default=None)
    op.alter_column("scanner_configurations", "value_weight", server_default=None)
    op.alter_column("scanner_results", "primary_score", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_results", "primary_score")
    op.drop_column("scanner_configurations", "value_weight")
    op.drop_column("scanner_configurations", "momentum_weight")
    # ### end Alembic commands ###
