"""live arming mode

Revision ID: ea234ccbc752
Revises: 194cbd855af8
Create Date: 2026-07-19 16:19:39.642478+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ea234ccbc752'
down_revision: str | None = '194cbd855af8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills any existing arming rows to the safe default
    # (approval-required); new rows get their value from the application.
    op.add_column(
        'live_arming_sessions',
        sa.Column(
            'mode',
            sa.String(length=24),
            nullable=False,
            server_default='live_approval_required',
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_arming_sessions', 'mode')
    # ### end Alembic commands ###
