"""scanner and proposals

Revision ID: 045d3b68c4f1
Revises: 5c93d1e5d2d6
Create Date: 2026-07-17 16:39:48.991387+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.models.base

revision: str = "045d3b68c4f1"
down_revision: str | None = "5c93d1e5d2d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scanner_configurations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("included_exchanges", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("included_currencies", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("include_stocks", sa.Boolean(), nullable=False),
        sa.Column("include_etfs", sa.Boolean(), nullable=False),
        sa.Column("min_price", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("min_avg_traded_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("max_instruments_per_scan", sa.Integer(), nullable=False),
        sa.Column("trading212_only", sa.Boolean(), nullable=False),
        sa.Column("weights", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("thresholds", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("benchmark_symbol", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scanner_configurations")),
        sa.UniqueConstraint("name", name="uq_scanner_configurations_name"),
    )
    op.create_table(
        "scanner_runs",
        sa.Column("configuration_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("instruments_considered", sa.Integer(), nullable=False),
        sa.Column("instruments_scored", sa.Integer(), nullable=False),
        sa.Column("instruments_skipped", sa.Integer(), nullable=False),
        sa.Column("screening_candidates", sa.Integer(), nullable=False),
        sa.Column("watchlist_candidates", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("selection_reason", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["scanner_configurations.id"],
            name=op.f("fk_scanner_runs_configuration_id_scanner_configurations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scanner_runs")),
    )
    op.create_index(
        op.f("ix_scanner_runs_configuration_id"), "scanner_runs", ["configuration_id"], unique=False
    )
    op.create_index(
        "ix_scanner_runs_status_started", "scanner_runs", ["status", "started_at"], unique=False
    )
    op.create_table(
        "scanner_results",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("core_score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("trend_score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("momentum_score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("risk_score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("liquidity_score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("positioning_score", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("fundamental_score", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("classification", sa.String(length=24), nullable=False),
        sa.Column("data_completeness", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("data_freshness_days", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("candles_used", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=True),
        sa.Column("positive_signals", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("negative_signals", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("missing_information", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("metrics", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("is_trading212_tradable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_scanner_results_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scanner_runs.id"],
            name=op.f("fk_scanner_results_run_id_scanner_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scanner_results")),
    )
    op.create_index(
        "ix_scanner_results_classification", "scanner_results", ["classification"], unique=False
    )
    op.create_index(
        "ix_scanner_results_instrument", "scanner_results", ["instrument_id"], unique=False
    )
    op.create_index(op.f("ix_scanner_results_run_id"), "scanner_results", ["run_id"], unique=False)
    op.create_index(
        "ix_scanner_results_run_score", "scanner_results", ["run_id", "core_score"], unique=False
    )
    op.create_table(
        "trade_proposals",
        sa.Column("scanner_result_id", sa.Uuid(), nullable=True),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("proposed_quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("max_position_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("risk_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("risk_pct", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("indicative_entry_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("proposed_stop_price", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("broker", sa.String(length=24), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("duplicate_of_proposal_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_trade_proposals_approved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of_proposal_id"],
            ["trade_proposals.id"],
            name=op.f("fk_trade_proposals_duplicate_of_proposal_id_trade_proposals"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_trade_proposals_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scanner_result_id"],
            ["scanner_results.id"],
            name=op.f("fk_trade_proposals_scanner_result_id_scanner_results"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_proposals")),
    )
    op.create_index("ix_trade_proposals_expires", "trade_proposals", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_trade_proposals_instrument_id"), "trade_proposals", ["instrument_id"], unique=False
    )
    op.create_index(
        op.f("ix_trade_proposals_scanner_result_id"),
        "trade_proposals",
        ["scanner_result_id"],
        unique=False,
    )
    op.create_index("ix_trade_proposals_status", "trade_proposals", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trade_proposals_status", table_name="trade_proposals")
    op.drop_index(op.f("ix_trade_proposals_scanner_result_id"), table_name="trade_proposals")
    op.drop_index(op.f("ix_trade_proposals_instrument_id"), table_name="trade_proposals")
    op.drop_index("ix_trade_proposals_expires", table_name="trade_proposals")
    op.drop_table("trade_proposals")
    op.drop_index("ix_scanner_results_run_score", table_name="scanner_results")
    op.drop_index(op.f("ix_scanner_results_run_id"), table_name="scanner_results")
    op.drop_index("ix_scanner_results_instrument", table_name="scanner_results")
    op.drop_index("ix_scanner_results_classification", table_name="scanner_results")
    op.drop_table("scanner_results")
    op.drop_index("ix_scanner_runs_status_started", table_name="scanner_runs")
    op.drop_index(op.f("ix_scanner_runs_configuration_id"), table_name="scanner_runs")
    op.drop_table("scanner_runs")
    op.drop_table("scanner_configurations")
    # ### end Alembic commands ###
