"""insider sell penalty, and insider buying reweighted to 0.15

Splits insider activity into two mechanisms instead of one signed factor.

Buying stays a weighted factor and rises 0.05 -> 0.15. Selling becomes a
multiplicative penalty of up to 30% on the final score, stored per result so a
mark-down is explainable.

Why not simply weight the old signed factor higher: a weight big enough for
selling to bite also inflates every US stock with a buy, and because a missing
factor drops out and the rest renormalise, that inflation lands only on the
instruments that have filings at all. Modelled at 0.60 it put an average US name
with one insider buy above a UK name better on every other axis — ranking by
data availability rather than quality. A penalty only ever subtracts, so it can
be aggressive without that effect

Revision ID: b6372c75004c
Revises: c9db01668709
Create Date: 2026-07-29 03:26:42.469812+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "b6372c75004c"
down_revision: str | None = "c9db01668709"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_NEW_WEIGHTS = (
    '{"fundamental_value": 0.30, "price_cheapness": 0.17, "reversal": 0.17, '
    '"quality": 0.12, "sector": 0.09, "insider": 0.15}'
)
_OLD_WEIGHTS = (
    '{"fundamental_value": 0.33, "price_cheapness": 0.19, "reversal": 0.19, '
    '"quality": 0.14, "sector": 0.10, "insider": 0.05}'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_results",
        sa.Column("insider_sell_penalty", sa.Numeric(precision=12, scale=6), nullable=True),
    )
    op.execute(f"UPDATE scanner_configurations SET factor_weights = '{_NEW_WEIGHTS}'::jsonb")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"UPDATE scanner_configurations SET factor_weights = '{_OLD_WEIGHTS}'::jsonb")
    op.drop_column("scanner_results", "insider_sell_penalty")
    # ### end Alembic commands ###
