"""initial schema

Revision ID: 5c93d1e5d2d6
Revises:
Create Date: 2026-07-17 08:12:03.563723+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.models.base

revision: str = "5c93d1e5d2d6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The audit chain's ordering sequence. Autogenerate emits the column's
    # `nextval(...)` default but not the sequence itself, because the PK of
    # audit_events is a UUID and alembic only creates sequences implicitly for
    # integer primary keys. Without this, creating audit_events fails.
    op.execute("CREATE SEQUENCE IF NOT EXISTS audit_events_sequence_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchanges",
        sa.Column("mic", sa.String(length=4), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("calendar_name", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchanges")),
    )
    op.create_index(op.f("ix_exchanges_mic"), "exchanges", ["mic"], unique=True)
    op.create_table(
        "provider_health",
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("is_healthy", sa.Boolean(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_latency_ms", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_health")),
        sa.UniqueConstraint("provider", name="uq_provider_health_provider"),
    )
    op.create_table(
        "provider_usage",
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("requests_used", sa.Integer(), nullable=False),
        sa.Column("requests_failed", sa.Integer(), nullable=False),
        sa.Column("operational_limit", sa.Integer(), nullable=False),
        sa.Column("emergency_reserve", sa.Integer(), nullable=False),
        sa.Column("last_request_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_usage")),
        sa.UniqueConstraint("provider", "usage_date", name="uq_provider_usage_provider_date"),
    )
    op.create_index(
        op.f("ix_provider_usage_provider"), "provider_usage", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_provider_usage_usage_date"), "provider_usage", ["usage_date"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_events",
        sa.Column(
            "sequence",
            sa.BigInteger(),
            server_default=sa.text("nextval('audit_events_sequence_seq')"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_label", sa.String(length=120), nullable=True),
        sa.Column("subject_type", sa.String(length=40), nullable=True),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("trade_intent_id", sa.String(length=64), nullable=True),
        sa.Column("strategy_decision_id", sa.String(length=64), nullable=True),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("event_hash", name=op.f("uq_audit_events_event_hash")),
    )
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_kind_occurred", "audit_events", ["kind", "occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_sequence"), "audit_events", ["sequence"], unique=True)
    op.create_index(
        op.f("ix_audit_events_strategy_decision_id"),
        "audit_events",
        ["strategy_decision_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_subject", "audit_events", ["subject_type", "subject_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_trade_intent_id"), "audit_events", ["trade_intent_id"], unique=False
    )
    op.create_table(
        "broker_credentials",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("broker", sa.String(length=24), nullable=False),
        sa.Column("encrypted_api_key", sa.LargeBinary(), nullable=False),
        sa.Column("key_fingerprint", sa.String(length=8), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verification_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_broker_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_credentials")),
        sa.UniqueConstraint("user_id", "broker", name="uq_broker_credentials_user_broker"),
    )
    op.create_index(
        op.f("ix_broker_credentials_user_id"), "broker_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "instruments",
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("exchange_id", sa.Uuid(), nullable=True),
        sa.Column("exchange_ticker", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_unit", sa.String(length=3), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("sector", sa.String(length=120), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("identity_confirmed_by_user", sa.Boolean(), nullable=False),
        sa.Column("identity_resolution_note", sa.Text(), nullable=True),
        sa.Column("lifecycle_state", sa.String(length=24), nullable=False),
        sa.Column("lifecycle_note", sa.Text(), nullable=True),
        sa.Column("is_scanner_eligible", sa.Boolean(), nullable=False),
        sa.Column("is_bot_universe", sa.Boolean(), nullable=False),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspension_reason", sa.Text(), nullable=True),
        sa.Column("last_scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
            name=op.f("fk_instruments_exchange_id_exchanges"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("isin", "exchange_id", name="uq_instruments_isin_exchange"),
    )
    op.create_index(
        op.f("ix_instruments_exchange_id"), "instruments", ["exchange_id"], unique=False
    )
    op.create_index(
        op.f("ix_instruments_exchange_ticker"), "instruments", ["exchange_ticker"], unique=False
    )
    op.create_index(op.f("ix_instruments_isin"), "instruments", ["isin"], unique=False)
    op.create_index(
        op.f("ix_instruments_last_scanned_at"), "instruments", ["last_scanned_at"], unique=False
    )
    op.create_index(
        op.f("ix_instruments_lifecycle_state"), "instruments", ["lifecycle_state"], unique=False
    )
    op.create_index("ix_instruments_name_search", "instruments", ["name"], unique=False)
    op.create_table(
        "live_arming_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("armed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disarmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disarm_reason", sa.String(length=200), nullable=True),
        sa.Column("max_live_capital", sa.String(length=32), nullable=False),
        sa.Column("max_daily_loss", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_live_arming_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_arming_sessions")),
    )
    op.create_index(
        op.f("ix_live_arming_sessions_expires_at"),
        "live_arming_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_live_arming_sessions_user_id"), "live_arming_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "provider_credentials",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("encrypted_api_key", sa.LargeBinary(), nullable=False),
        sa.Column("key_fingerprint", sa.String(length=8), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verification_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_provider_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_credentials")),
        sa.UniqueConstraint("user_id", "provider", name="uq_provider_credentials_user_provider"),
    )
    op.create_index(
        op.f("ix_provider_credentials_user_id"), "provider_credentials", ["user_id"], unique=False
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", app.models.base.JSONBOrJSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_system_settings_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_settings")),
        sa.UniqueConstraint("key", name="uq_system_settings_key"),
    )
    op.create_index(op.f("ix_system_settings_key"), "system_settings", ["key"], unique=False)
    op.create_table(
        "trading_schedules",
        sa.Column("exchange_id", sa.Uuid(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("open_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_partial", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
            name=op.f("fk_trading_schedules_exchange_id_exchanges"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_schedules")),
        sa.UniqueConstraint(
            "exchange_id", "session_date", name="uq_trading_schedules_exchange_date"
        ),
    )
    op.create_index(
        op.f("ix_trading_schedules_exchange_id"), "trading_schedules", ["exchange_id"], unique=False
    )
    op.create_index(
        op.f("ix_trading_schedules_session_date"),
        "trading_schedules",
        ["session_date"],
        unique=False,
    )
    op.create_table(
        "user_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("reauthenticated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name="uq_user_sessions_token_hash"),
    )
    op.create_index(
        op.f("ix_user_sessions_expires_at"), "user_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "watchlists",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_watchlists_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlists")),
        sa.UniqueConstraint("user_id", "name", name="uq_watchlists_user_name"),
    )
    op.create_index(op.f("ix_watchlists_user_id"), "watchlists", ["user_id"], unique=False)
    op.create_table(
        "broker_instruments",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("broker", sa.String(length=24), nullable=False),
        sa.Column("broker_ticker", sa.String(length=64), nullable=False),
        sa.Column("broker_name", sa.String(length=300), nullable=True),
        sa.Column("broker_isin", sa.String(length=12), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("is_currently_available", sa.Boolean(), nullable=False),
        sa.Column("min_quantity", sa.String(length=32), nullable=True),
        sa.Column("quantity_step", sa.String(length=32), nullable=True),
        sa.Column("supports_fractional", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_payload", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_broker_instruments_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_instruments")),
        sa.UniqueConstraint("broker", "broker_ticker", name="uq_broker_instruments_broker_ticker"),
    )
    op.create_index(
        op.f("ix_broker_instruments_broker"), "broker_instruments", ["broker"], unique=False
    )
    op.create_index(
        "ix_broker_instruments_instrument_broker",
        "broker_instruments",
        ["instrument_id", "broker"],
        unique=False,
    )
    op.create_index(
        op.f("ix_broker_instruments_instrument_id"),
        "broker_instruments",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "candles",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("provider_symbol", sa.String(length=64), nullable=False),
        sa.Column("interval", sa.String(length=8), nullable=False),
        sa.Column("data_series_type", sa.String(length=12), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("volume", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_unit", sa.String(length=3), nullable=False),
        sa.Column("is_adjusted", sa.Boolean(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("quality_status", sa.String(length=16), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_candles_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candles")),
        sa.UniqueConstraint(
            "instrument_id",
            "interval",
            "timestamp",
            "data_series_type",
            name="uq_candles_instrument_interval_timestamp_series",
        ),
    )
    op.create_index(
        "ix_candles_instrument_interval_timestamp",
        "candles",
        ["instrument_id", "interval", "timestamp"],
        unique=False,
    )
    op.create_index("ix_candles_quality", "candles", ["quality_status"], unique=False)
    op.create_table(
        "corporate_actions",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=16), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("ratio", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_corporate_actions_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_actions")),
        sa.UniqueConstraint(
            "instrument_id",
            "action_type",
            "ex_date",
            name="uq_corporate_actions_instrument_type_exdate",
        ),
    )
    op.create_index(
        op.f("ix_corporate_actions_ex_date"), "corporate_actions", ["ex_date"], unique=False
    )
    op.create_index(
        op.f("ix_corporate_actions_instrument_id"),
        "corporate_actions",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "data_quality_events",
        sa.Column("instrument_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=True),
        sa.Column("interval", sa.String(length=8), nullable=True),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("context", app.models.base.JSONBOrJSON(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_data_quality_events_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_events")),
    )
    op.create_index(
        op.f("ix_data_quality_events_instrument_id"),
        "data_quality_events",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        "ix_data_quality_events_instrument_kind",
        "data_quality_events",
        ["instrument_id", "kind"],
        unique=False,
    )
    op.create_index(
        "ix_data_quality_events_unresolved", "data_quality_events", ["resolved_at"], unique=False
    )
    op.create_table(
        "fundamental_snapshots",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("market_cap", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("trailing_pe", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("price_to_book", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("dividend_yield", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("revenue_growth", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("earnings_growth", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("profit_margin", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("debt_to_equity", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_fundamental_snapshots_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fundamental_snapshots")),
        sa.UniqueConstraint(
            "instrument_id", "provider", "as_of", name="uq_fundamental_snapshots_instrument_asof"
        ),
    )
    op.create_index(
        op.f("ix_fundamental_snapshots_as_of"), "fundamental_snapshots", ["as_of"], unique=False
    )
    op.create_index(
        op.f("ix_fundamental_snapshots_instrument_id"),
        "fundamental_snapshots",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "market_data_mappings",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("provider_symbol", sa.String(length=64), nullable=False),
        sa.Column("price_unit", sa.String(length=3), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_signal_source", sa.Boolean(), nullable=False),
        sa.Column("resolution_method", sa.String(length=64), nullable=True),
        sa.Column("confirmed_by_user", sa.Boolean(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_market_data_mappings_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_data_mappings")),
        sa.UniqueConstraint(
            "instrument_id",
            "provider",
            "provider_symbol",
            name="uq_market_data_mappings_instrument_provider_symbol",
        ),
    )
    op.create_index(
        op.f("ix_market_data_mappings_instrument_id"),
        "market_data_mappings",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_data_mappings_provider"), "market_data_mappings", ["provider"], unique=False
    )
    op.create_index(
        "ix_market_data_mappings_provider_symbol",
        "market_data_mappings",
        ["provider", "provider_symbol"],
        unique=False,
    )
    op.create_table(
        "watchlist_instruments",
        sa.Column("watchlist_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_watchlist_instruments_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
            name=op.f("fk_watchlist_instruments_watchlist_id_watchlists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_instruments")),
        sa.UniqueConstraint(
            "watchlist_id", "instrument_id", name="uq_watchlist_instruments_watchlist_instrument"
        ),
    )
    op.create_index(
        op.f("ix_watchlist_instruments_instrument_id"),
        "watchlist_instruments",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watchlist_instruments_watchlist_id"),
        "watchlist_instruments",
        ["watchlist_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # -- Audit immutability (§17) ---------------------------------------------
    #
    # The audit log must be append-only. Enforcing that only in application code
    # would mean the guarantee evaporates the moment anything else touches the
    # database — a migration, a psql session, or an application bug. A trigger
    # makes UPDATE and DELETE fail regardless of who attempts them.
    #
    # This is not protection against a determined superuser (who can drop the
    # trigger), and is not meant to be. It defends against the realistic
    # failure: ordinary code, or an ordinary mistake, silently rewriting
    # history that a financial audit depends on.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_events_reject_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_events is append-only: % is not permitted (§17). '
                'Correct the record by appending a compensating event.',
                TG_OP
            USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_immutable
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION audit_events_reject_mutation();
        """
    )
    # TRUNCATE bypasses row-level triggers entirely — it is a table operation,
    # not a row one — so the trigger above would let `TRUNCATE audit_events`
    # erase the whole log unchallenged. A statement-level trigger is the only
    # thing that catches it.
    op.execute(
        """
        CREATE TRIGGER audit_events_no_truncate
        BEFORE TRUNCATE ON audit_events
        FOR EACH STATEMENT EXECUTE FUNCTION audit_events_reject_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_truncate ON audit_events")
    op.execute("DROP TRIGGER IF EXISTS audit_events_immutable ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit_events_reject_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watchlist_instruments_watchlist_id"), table_name="watchlist_instruments")
    op.drop_index(
        op.f("ix_watchlist_instruments_instrument_id"), table_name="watchlist_instruments"
    )
    op.drop_table("watchlist_instruments")
    op.drop_index("ix_market_data_mappings_provider_symbol", table_name="market_data_mappings")
    op.drop_index(op.f("ix_market_data_mappings_provider"), table_name="market_data_mappings")
    op.drop_index(op.f("ix_market_data_mappings_instrument_id"), table_name="market_data_mappings")
    op.drop_table("market_data_mappings")
    op.drop_index(
        op.f("ix_fundamental_snapshots_instrument_id"), table_name="fundamental_snapshots"
    )
    op.drop_index(op.f("ix_fundamental_snapshots_as_of"), table_name="fundamental_snapshots")
    op.drop_table("fundamental_snapshots")
    op.drop_index("ix_data_quality_events_unresolved", table_name="data_quality_events")
    op.drop_index("ix_data_quality_events_instrument_kind", table_name="data_quality_events")
    op.drop_index(op.f("ix_data_quality_events_instrument_id"), table_name="data_quality_events")
    op.drop_table("data_quality_events")
    op.drop_index(op.f("ix_corporate_actions_instrument_id"), table_name="corporate_actions")
    op.drop_index(op.f("ix_corporate_actions_ex_date"), table_name="corporate_actions")
    op.drop_table("corporate_actions")
    op.drop_index("ix_candles_quality", table_name="candles")
    op.drop_index("ix_candles_instrument_interval_timestamp", table_name="candles")
    op.drop_table("candles")
    op.drop_index(op.f("ix_broker_instruments_instrument_id"), table_name="broker_instruments")
    op.drop_index("ix_broker_instruments_instrument_broker", table_name="broker_instruments")
    op.drop_index(op.f("ix_broker_instruments_broker"), table_name="broker_instruments")
    op.drop_table("broker_instruments")
    op.drop_index(op.f("ix_watchlists_user_id"), table_name="watchlists")
    op.drop_table("watchlists")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_trading_schedules_session_date"), table_name="trading_schedules")
    op.drop_index(op.f("ix_trading_schedules_exchange_id"), table_name="trading_schedules")
    op.drop_table("trading_schedules")
    op.drop_index(op.f("ix_system_settings_key"), table_name="system_settings")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_provider_credentials_user_id"), table_name="provider_credentials")
    op.drop_table("provider_credentials")
    op.drop_index(op.f("ix_live_arming_sessions_user_id"), table_name="live_arming_sessions")
    op.drop_index(op.f("ix_live_arming_sessions_expires_at"), table_name="live_arming_sessions")
    op.drop_table("live_arming_sessions")
    op.drop_index("ix_instruments_name_search", table_name="instruments")
    op.drop_index(op.f("ix_instruments_lifecycle_state"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_last_scanned_at"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_isin"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_exchange_ticker"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_exchange_id"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_broker_credentials_user_id"), table_name="broker_credentials")
    op.drop_table("broker_credentials")
    op.drop_index(op.f("ix_audit_events_trade_intent_id"), table_name="audit_events")
    op.drop_index("ix_audit_events_subject", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_strategy_decision_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_sequence"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index("ix_audit_events_kind_occurred", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_provider_usage_usage_date"), table_name="provider_usage")
    op.drop_index(op.f("ix_provider_usage_provider"), table_name="provider_usage")
    op.drop_table("provider_usage")
    op.drop_table("provider_health")
    op.drop_index(op.f("ix_exchanges_mic"), table_name="exchanges")
    op.drop_table("exchanges")
    # ### end Alembic commands ###

    op.execute("DROP SEQUENCE IF EXISTS audit_events_sequence_seq")
