"""scanner insider factor

Adds `insider_score` and reweights the final blend from five factors to six.

The existing five are shaved proportionally rather than one of them funding the
new factor, so their balance relative to each other is unchanged and a stock
with no Form 4 filings scores exactly as it did before — the blend drops missing
factors and renormalises.

Insider gets only 0.05 deliberately. It is the one factor that is absent for
most of the catalogue (Form 4 is US-only; there is no UK equivalent), and a
factor that fires for a minority should not swing the ranking when it does

Revision ID: c9db01668709
Revises: ef244a4757ff
Create Date: 2026-07-29 02:48:59.198025+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "c9db01668709"
down_revision: str | None = "ef244a4757ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_NEW_WEIGHTS = (
    '{"fundamental_value": 0.33, "price_cheapness": 0.19, "reversal": 0.19, '
    '"quality": 0.14, "sector": 0.10, "insider": 0.05}'
)
_OLD_WEIGHTS = (
    '{"fundamental_value": 0.35, "price_cheapness": 0.20, "reversal": 0.20, '
    '"quality": 0.15, "sector": 0.10}'
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_results",
        sa.Column("insider_score", sa.Numeric(precision=12, scale=6), nullable=True),
    )
    op.execute(f"UPDATE scanner_configurations SET factor_weights = '{_NEW_WEIGHTS}'::jsonb")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"UPDATE scanner_configurations SET factor_weights = '{_OLD_WEIGHTS}'::jsonb")
    op.drop_column("scanner_results", "insider_score")
    # ### end Alembic commands ###
