"""risk engine, paper broker, trade intents

Revision ID: 03a42e4bbda3
Revises: 0f75d2ac25fb
Create Date: 2026-07-18 04:12:18.333963+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import app.models.base

revision: str = '03a42e4bbda3'
down_revision: str | None = '0f75d2ac25fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_broker_accounts',
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('starting_cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_broker_accounts')),
    sa.UniqueConstraint('currency', name='uq_paper_broker_accounts_currency')
    )
    op.create_table('risk_configurations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('risk_per_trade_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('atr_stop_multiplier', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('max_position_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('max_instrument_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('max_total_open_risk_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('max_portfolio_exposure_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('monetary_position_cap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('consecutive_loss_cooldown', sa.Integer(), nullable=False),
    sa.Column('max_daily_realised_loss_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('max_portfolio_drawdown_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('correlation_benchmark_symbol', sa.String(length=32), nullable=False),
    sa.Column('correlation_window_short', sa.Integer(), nullable=False),
    sa.Column('correlation_window_long', sa.Integer(), nullable=False),
    sa.Column('correlation_threshold', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('max_portfolio_sp500_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('extra', app.models.base.JSONBOrJSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_configurations')),
    sa.UniqueConstraint('name', name='uq_risk_configurations_name')
    )
    op.create_table('paper_broker_orders',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=False),
    sa.Column('broker_ticker', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('client_reference', sa.String(length=128), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_broker_accounts.id'], name=op.f('fk_paper_broker_orders_account_id_paper_broker_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_broker_orders')),
    sa.UniqueConstraint('broker_order_id', name='uq_paper_broker_orders_broker_order_id')
    )
    op.create_index('ix_paper_broker_orders_account_status', 'paper_broker_orders', ['account_id', 'status'], unique=False)
    op.create_table('paper_broker_positions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('broker_ticker', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_broker_accounts.id'], name=op.f('fk_paper_broker_positions_account_id_paper_broker_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_broker_positions')),
    sa.UniqueConstraint('account_id', 'broker_ticker', name='uq_paper_broker_positions_account_ticker')
    )
    op.create_index(op.f('ix_paper_broker_positions_account_id'), 'paper_broker_positions', ['account_id'], unique=False)
    op.create_table('risk_halts',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_key', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('activated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_user_id'], ['users.id'], name=op.f('fk_risk_halts_activated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cleared_by_user_id'], ['users.id'], name=op.f('fk_risk_halts_cleared_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_risk_halts_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_halts'))
    )
    op.create_index('ix_risk_halts_active', 'risk_halts', ['is_active'], unique=False)
    op.create_index(op.f('ix_risk_halts_instrument_id'), 'risk_halts', ['instrument_id'], unique=False)
    op.create_index('ix_risk_halts_scope_instrument', 'risk_halts', ['scope', 'instrument_id'], unique=False)
    op.create_table('trade_intents',
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('broker', sa.String(length=24), nullable=False),
    sa.Column('client_reference', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('filled_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_trade_intents_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], name=op.f('fk_trade_intents_proposal_id_trade_proposals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_intents')),
    sa.UniqueConstraint('client_reference', name='uq_trade_intents_client_reference')
    )
    op.create_index('ix_trade_intents_instrument', 'trade_intents', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_trade_intents_proposal_id'), 'trade_intents', ['proposal_id'], unique=False)
    op.create_index('ix_trade_intents_status', 'trade_intents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_intents_status', table_name='trade_intents')
    op.drop_index(op.f('ix_trade_intents_proposal_id'), table_name='trade_intents')
    op.drop_index('ix_trade_intents_instrument', table_name='trade_intents')
    op.drop_table('trade_intents')
    op.drop_index('ix_risk_halts_scope_instrument', table_name='risk_halts')
    op.drop_index(op.f('ix_risk_halts_instrument_id'), table_name='risk_halts')
    op.drop_index('ix_risk_halts_active', table_name='risk_halts')
    op.drop_table('risk_halts')
    op.drop_index(op.f('ix_paper_broker_positions_account_id'), table_name='paper_broker_positions')
    op.drop_table('paper_broker_positions')
    op.drop_index('ix_paper_broker_orders_account_status', table_name='paper_broker_orders')
    op.drop_table('paper_broker_orders')
    op.drop_table('risk_configurations')
    op.drop_table('paper_broker_accounts')
    # ### end Alembic commands ###
