"""stops trailing, reconciliation halts, eod summaries

Revision ID: d72851034a39
Revises: 03a42e4bbda3
Create Date: 2026-07-18 15:36:00.940009+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd72851034a39'
down_revision: str | None = '03a42e4bbda3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_account_summaries',
    sa.Column('broker', sa.String(length=24), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('invested', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unrealised_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('realised_pnl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('equity_change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('trades_today', sa.Integer(), nullable=False),
    sa.Column('active_halts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_account_summaries')),
    sa.UniqueConstraint('broker', 'summary_date', name='uq_daily_account_summaries_broker_date')
    )
    op.create_index(op.f('ix_daily_account_summaries_summary_date'), 'daily_account_summaries', ['summary_date'], unique=False)
    # server_default backfills any already-seeded configuration row so the NOT
    # NULL constraint is satisfiable; new rows get their value from the model.
    op.add_column(
        'risk_configurations',
        sa.Column(
            'trailing_stop_enabled', sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    op.add_column(
        'risk_configurations',
        sa.Column('max_holding_days', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('trade_intents', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trade_intents', sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('trade_intents', sa.Column('exit_reason', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_intents', 'exit_reason')
    op.drop_column('trade_intents', 'exit_price')
    op.drop_column('trade_intents', 'closed_at')
    op.drop_column('risk_configurations', 'max_holding_days')
    op.drop_column('risk_configurations', 'trailing_stop_enabled')
    op.drop_index(op.f('ix_daily_account_summaries_summary_date'), table_name='daily_account_summaries')
    op.drop_table('daily_account_summaries')
    # ### end Alembic commands ###
